# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0+1.21.1
maven_group=net.rpgadvanceddifficulty
archives_base_name=rpgadvanceddifficulty

# Dependencies
fabric_version=0.116.11+1.21.1
cloth_config_version=15.0.140
mod_menu_version=11.0.3

systemProp.https.protocols=TLSv1.2,TLSv1.3
